# 🛢️ ETL Pipeline: Dampak Harga Minyak Global terhadap Inflasi Indonesia

**Deskripsi Project:**  
Pipeline ETL (Extract, Transform, Load) yang membangun dataset terintegrasi antara harga minyak global (Crude Oil), kurs USD/IDR, dan data inflasi bulanan Indonesia per daerah. Dataset akhir disimpan ke database PostgreSQL Aiven untuk analisis lebih lanjut.

**Sumber Data:**
- `crude-oil-price.csv` — Harga minyak mentah global (bulanan, USD)
- `USD_IDR_Historical_Data.csv` — Kurs USD ke IDR (bulanan)
- `Inflasi_Bulanan__M-to-M__YYYY.csv` — Inflasi bulanan per daerah di Indonesia (2020–2026)

**Alur ETL:**
```
[Extract] → Baca CSV → Validasi
[Transform] → Cleaning → Integrasi → Feature Engineering
[Load] → Simpan ke PostgreSQL Aiven
```

---

## 1. 📦 Import Library

Mengimpor seluruh library yang dibutuhkan untuk proses ETL.

In [2]:
import os
import logging
import warnings
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import psycopg2

warnings.filterwarnings("ignore")

# ── Konfigurasi logging ──────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger(__name__)

logger.info("  Seluruh library berhasil diimpor.")
print(f"  pandas  : {pd.__version__}")
print(f"  numpy   : {np.__version__}")

2026-06-06 03:21:26 [INFO]   Seluruh library berhasil diimpor.

  pandas  : 3.0.3
  numpy   : 2.4.6

## 2. ⚙️ Konfigurasi Project

### 2.1 Konfigurasi Environment Variable

Credential database dibaca dari file `.env`

In [2]:
# ── Load environment variables dari file .env ────────────────────────────────
load_dotenv()

DB_CONFIG = {
    "host"    : os.getenv("AIVEN_HOST"),
    "port"    : os.getenv("AIVEN_PORT", "5432"),
    "database": os.getenv("AIVEN_DATABASE"),
    "user"    : os.getenv("AIVEN_USER"),
    "password": os.getenv("AIVEN_PASSWORD"),
}

# Validasi keberadaan env variable
_missing = [k for k, v in DB_CONFIG.items() if not v]
if _missing:
    logger.warning(f"  Env variable belum diisi: {_missing}. Load akan di-skip.")
else:
    logger.info("  Semua credential database berhasil dimuat dari .env.")

2026-06-05 18:49:42 [INFO]   Semua credential database berhasil dimuat dari .env.

### 2.2 Konfigurasi Path File CSV

In [3]:
# ── Path direktori data ──────────────────────────────────────────────────────
DATA_DIR = Path("data")            # Sesuaikan jika file CSV berada di direktori berbeda
# DATA_DIR = Path(".")             # Uncomment jika file CSV ada di direktori yang sama dengan notebook

# ── Path masing-masing dataset ───────────────────────────────────────────────
PATH_OIL   = DATA_DIR / "crude-oil-price.csv"
PATH_KURS  = DATA_DIR / "USD_IDR Historical Data.csv"

INFLASI_YEARS = [2020, 2021, 2022, 2023, 2024, 2025, 2026]
INFLASI_PATHS = {
    yr: DATA_DIR / f"Inflasi Bulanan (M-to-M), {yr}.csv"
    for yr in INFLASI_YEARS
}

# ── Nama tabel PostgreSQL ────────────────────────────────────────────────────
TABLE_NAME = "inflasi_minyak_indonesia"

logger.info(f"  Direktori data : {DATA_DIR.resolve()}")
logger.info(f"  Tabel target   : {TABLE_NAME}")

2026-06-05 18:49:47 [INFO]   Direktori data : D:\Kuliah\Semester 4\DataEngineering\projectUAS\UAS_DataEngineering\data
2026-06-05 18:49:47 [INFO]   Tabel target   : inflasi_minyak_indonesia

## 3. 📥 Extract

Proses membaca seluruh file CSV secara otomatis, lengkap dengan validasi, preview, dan logging.

In [4]:
def load_dataset(filepath: Path, label: str = "", **read_kwargs) -> pd.DataFrame:
    """
    Membaca file CSV dan menampilkan informasi dasar dataset.

    Parameters
    ----------
    filepath  : Path ke file CSV.
    label     : Nama dataset untuk keperluan logging.
    **read_kwargs : Argumen tambahan yang diteruskan ke pd.read_csv().

    Returns
    -------
    pd.DataFrame hasil pembacaan, atau DataFrame kosong jika file tidak ditemukan.
    """
    label = label or filepath.name
    try:
        df = pd.read_csv(filepath, **read_kwargs)
        logger.info(f"  [{label}] Berhasil dibaca → shape {df.shape}")
        return df
    except FileNotFoundError:
        logger.error(f"  [{label}] File tidak ditemukan: {filepath}")
        return pd.DataFrame()
    except Exception as e:
        logger.error(f"  [{label}] Gagal membaca file: {e}")
        return pd.DataFrame()


def preview_dataset(df: pd.DataFrame, label: str = "", n: int = 3) -> None:
    """Menampilkan preview, shape, dan tipe data sebuah DataFrame."""
    sep = "─" * 60
    print(f"\n{sep}")
    print(f"  Dataset : {label}")
    print(f"  Shape   : {df.shape[0]:,} baris × {df.shape[1]} kolom")
    print(sep)
    print("\n  Preview (head):")
    display(df.head(n))
    print("\n  Tipe Data:")
    print(df.dtypes.to_string())
    print(f"\n  Missing Values:\n{df.isnull().sum().to_string()}")

### 3.1 Extract — Harga Minyak Global

In [5]:
raw_oil = load_dataset(PATH_OIL, label="Crude Oil Price")
preview_dataset(raw_oil, label="Crude Oil Price")

2026-06-05 18:49:57 [INFO]   [Crude Oil Price] Berhasil dibaca → shape (517, 4)

────────────────────────────────────────────────────────────
  Dataset : Crude Oil Price
  Shape   : 517 baris × 4 kolom
────────────────────────────────────────────────────────────

  Preview (head):

                        date  price  percentChange  change
0  1983-03-01 00:00:00+00:00  29.27            NaN     NaN
1  1983-04-01 00:00:00+00:00  30.63          4.646    1.36
2  1983-05-01 00:00:00+00:00  30.25         -1.241   -0.38

  Tipe Data:
date                 str
price            float64
percentChange    float64
change           float64

  Missing Values:
date             0
price            0
percentChange    1
change           1

### 3.2 Extract — Kurs USD/IDR

In [6]:
raw_kurs = load_dataset(PATH_KURS, label="USD/IDR Exchange Rate")
preview_dataset(raw_kurs, label="USD/IDR Exchange Rate")

2026-06-05 18:49:59 [INFO]   [USD/IDR Exchange Rate] Berhasil dibaca → shape (75, 7)

────────────────────────────────────────────────────────────
  Dataset : USD/IDR Exchange Rate
  Shape   : 75 baris × 7 kolom
────────────────────────────────────────────────────────────

  Preview (head):

         Date     Price      Open      High       Low  Vol. Change %
0  03/01/2026  16,929.7  16,822.5  16,974.4  16,814.5   NaN    0.98%
1  02/01/2026  16,765.0  16,790.0  16,960.0  16,732.5   NaN   -0.12%
2  01/01/2026  16,785.0  16,675.0  16,987.5  16,675.0   NaN    0.66%

  Tipe Data:
Date            str
Price           str
Open            str
High            str
Low             str
Vol.        float64
Change %        str

  Missing Values:
Date         0
Price        0
Open         0
High         0
Low          0
Vol.        75
Change %     0

### 3.3 Extract — Data Inflasi Bulanan (Multi-Year)

Data inflasi terdiri dari 7 file CSV (2020–2026), masing-masing dengan format pivot (wide).  
Seluruh file dibaca sekaligus dan disimpan dalam dictionary `raw_inflasi`.

In [7]:
raw_inflasi: dict[int, pd.DataFrame] = {}

for year, path in INFLASI_PATHS.items():
    df = load_dataset(path, label=f"Inflasi {year}")
    if not df.empty:
        raw_inflasi[year] = df

logger.info(f"  Total file inflasi berhasil dibaca: {len(raw_inflasi)} / {len(INFLASI_PATHS)}")

# Preview salah satu tahun sebagai contoh
if raw_inflasi:
    contoh_year = list(raw_inflasi.keys())[0]
    preview_dataset(raw_inflasi[contoh_year], label=f"Inflasi {contoh_year} (raw)")

2026-06-05 18:50:02 [INFO]   [Inflasi 2020] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   [Inflasi 2021] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   [Inflasi 2022] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   [Inflasi 2023] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   [Inflasi 2024] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   [Inflasi 2025] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   [Inflasi 2026] Berhasil dibaca → shape (155, 14)
2026-06-05 18:50:02 [INFO]   Total file inflasi berhasil dibaca: 7 / 7

────────────────────────────────────────────────────────────
  Dataset : Inflasi 2020 (raw)
  Shape   : 155 baris × 14 kolom
────────────────────────────────────────────────────────────

  Preview (head):

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Inflasi Bulanan (M-to-M) (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan

  Tipe Data:
Kota Inflasi    str
Unnamed: 1      str
Unnamed: 2      str
Unnamed: 3      str
Unnamed: 4      str
Unnamed: 5      str
Unnamed: 6      str
Unnamed: 7      str
Unnamed: 8      str
Unnamed: 9      str
Unnamed: 10     str
Unnamed: 11     str
Unnamed: 12     str
Unnamed: 13     str

  Missing Values:
Kota Inflasi    3
Unnamed: 1      0
Unnamed: 2      2
Unnamed: 3      2
Unnamed: 4      2
Unnamed: 5      2
Unnamed: 6      2
Unnamed: 7      2
Unnamed: 8      2
Unnamed: 9      2
Unnamed: 10     2
Unnamed: 11     2
Unnamed: 12     2
Unnamed: 13     2

## 4. 🔄 Transform

Proses transformasi mencakup:
1. **Data Cleaning** per dataset
2. **Integrasi** ketiga dataset berdasarkan tanggal/bulan
3. **Feature Engineering** — penambahan kolom turunan

---

### 4.1 Transform — Harga Minyak Global

In [8]:
BULAN_ID = {
    "Januari": 1, "Februari": 2, "Maret": 3,    "April": 4,
    "Mei": 5,     "Juni": 6,     "Juli": 7,      "Agustus": 8,
    "September": 9,"Oktober": 10, "November": 11, "Desember": 12,
}

def clean_oil(df: pd.DataFrame) -> pd.DataFrame:
    """
    Membersihkan dan menstandarkan dataset harga minyak global.

    Langkah:
    - Standardisasi nama kolom
    - Konversi kolom tanggal ke datetime
    - Hapus duplikat dan missing pada kolom kunci
    - Sorting berdasarkan tanggal
    - Filter hanya data tahun 2020–2026 agar sesuai rentang inflasi
    - Simpan kolom tahun dan bulan

    Returns
    -------
    pd.DataFrame dengan kolom:
        tanggal, tahun, bulan, harga_minyak_usd, perubahan_persen_minyak
    """
    df = df.copy()

    # Standardisasi nama kolom → snake_case
    df.columns = ["tanggal", "harga_minyak_usd", "perubahan_persen_minyak", "perubahan_nominal_minyak"]

    # Konversi tanggal (format: '1983-03-01 00:00:00+00:00')
    df["tanggal"] = pd.to_datetime(df["tanggal"], utc=True).dt.tz_localize(None)
    df["tanggal"] = df["tanggal"].dt.normalize()           # Hapus jam

    # Hapus duplikat
    before = len(df)
    df = df.drop_duplicates(subset=["tanggal"])
    logger.info(f"  [Oil] Duplikat dihapus: {before - len(df)} baris")

    # Hapus baris tanpa harga
    df = df.dropna(subset=["harga_minyak_usd"])

    # Validasi tipe numerik
    df["harga_minyak_usd"] = pd.to_numeric(df["harga_minyak_usd"], errors="coerce")
    df["perubahan_persen_minyak"] = pd.to_numeric(df["perubahan_persen_minyak"], errors="coerce")

    # Filter rentang tahun 2020–2026
    df = df[(df["tanggal"].dt.year >= 2020) & (df["tanggal"].dt.year <= 2026)]

    # Tambah kolom tahun & bulan
    df["tahun"] = df["tanggal"].dt.year
    df["bulan"] = df["tanggal"].dt.month

    # Kolom year_month untuk join
    df["year_month"] = df["tanggal"].dt.to_period("M")

    # Sorting
    df = df.sort_values("tanggal").reset_index(drop=True)

    # Drop kolom yang tidak dipakai lebih lanjut
    df = df.drop(columns=["perubahan_nominal_minyak"])

    logger.info(f"  [Oil] Cleaning selesai → shape {df.shape}")
    return df


clean_oil_df = clean_oil(raw_oil)
print(clean_oil_df.head())
print("\nShape:", clean_oil_df.shape)
print("\nDtypes:")
print(clean_oil_df.dtypes)

2026-06-05 18:50:07 [INFO]   [Oil] Duplikat dihapus: 0 baris
2026-06-05 18:50:07 [INFO]   [Oil] Cleaning selesai → shape (75, 6)

     tanggal  harga_minyak_usd  perubahan_persen_minyak  tahun  bulan  \
0 2020-01-01             51.56                  -15.135   2020      1
1 2020-02-01             44.76                  -13.189   2020      2
2 2020-03-01             20.48                  -54.245   2020      3
3 2020-04-01             18.84                   -8.008   2020      4
4 2020-05-01             35.49                   88.376   2020      5

  year_month
0    2020-01
1    2020-02
2    2020-03
3    2020-04
4    2020-05

Shape: (75, 6)

Dtypes:
tanggal                    datetime64[us]
harga_minyak_usd                  float64
perubahan_persen_minyak           float64
tahun                               int32
bulan                               int32
year_month                      period[M]
dtype: object

### 4.2 Transform — Kurs USD/IDR

In [9]:
def clean_kurs(df: pd.DataFrame) -> pd.DataFrame:
    """
    Membersihkan dan menstandarkan dataset kurs USD/IDR.

    Langkah:
    - Standardisasi nama kolom
    - Bersihkan format nilai mata uang (koma ribuan, simbol %)
    - Konversi tipe data ke numerik
    - Konversi tanggal ke datetime (format: '03/01/2026' = MM/DD/YYYY)
    - Hapus duplikat, handle missing
    - Sorting berdasarkan tanggal

    Returns
    -------
    pd.DataFrame dengan kolom:
        tanggal, tahun, bulan, kurs_usd_idr, year_month
    """
    df = df.copy()

    # Standardisasi nama kolom
    df.columns = ["tanggal", "kurs_usd_idr", "open_kurs", "high_kurs", "low_kurs", "volume", "perubahan_persen_kurs"]

    # Bersihkan format koma ribuan pada kolom numerik (16,929.7 → 16929.7)
    for col in ["kurs_usd_idr", "open_kurs", "high_kurs", "low_kurs"]:
        df[col] = df[col].astype(str).str.replace(",", "", regex=False)
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Bersihkan format persen pada change % ('0.98%' → 0.98)
    df["perubahan_persen_kurs"] = (
        df["perubahan_persen_kurs"]
        .astype(str)
        .str.replace("%", "", regex=False)
        .str.strip()
    )
    df["perubahan_persen_kurs"] = pd.to_numeric(df["perubahan_persen_kurs"], errors="coerce")

    # Konversi tanggal — format MM/DD/YYYY
    df["tanggal"] = pd.to_datetime(df["tanggal"], format="%m/%d/%Y")

    # Hapus duplikat
    before = len(df)
    df = df.drop_duplicates(subset=["tanggal"])
    logger.info(f"  [Kurs] Duplikat dihapus: {before - len(df)} baris")

    # Hapus baris tanpa kurs
    df = df.dropna(subset=["kurs_usd_idr"])

    # Kolom tahun, bulan, year_month
    df["tahun"] = df["tanggal"].dt.year
    df["bulan"] = df["tanggal"].dt.month
    df["year_month"] = df["tanggal"].dt.to_period("M")

    # Hanya simpan kolom yang relevan
    df = df[["tanggal", "tahun", "bulan", "kurs_usd_idr", "perubahan_persen_kurs", "year_month"]]

    # Sorting
    df = df.sort_values("tanggal").reset_index(drop=True)

    logger.info(f"  [Kurs] Cleaning selesai → shape {df.shape}")
    return df


clean_kurs_df = clean_kurs(raw_kurs)
print(clean_kurs_df.head())
print("\nDtypes:")
print(clean_kurs_df.dtypes)

2026-06-05 18:50:14 [INFO]   [Kurs] Duplikat dihapus: 0 baris
2026-06-05 18:50:14 [INFO]   [Kurs] Cleaning selesai → shape (75, 6)

     tanggal  tahun  bulan  kurs_usd_idr  perubahan_persen_kurs year_month
0 2020-01-01   2020      1       13650.0                  -1.66    2020-01
1 2020-02-01   2020      2       14340.0                   5.05    2020-02
2 2020-03-01   2020      3       16300.0                  13.67    2020-03
3 2020-04-01   2020      4       14825.0                  -9.05    2020-04
4 2020-05-01   2020      5       14575.0                  -1.69    2020-05

Dtypes:
tanggal                  datetime64[us]
tahun                             int32
bulan                             int32
kurs_usd_idr                    float64
perubahan_persen_kurs           float64
year_month                    period[M]
dtype: object

### 4.3 Transform — Inflasi Bulanan (Pivot → Long Format)

File inflasi menggunakan format **wide/pivot** (bulan sebagai kolom). Data perlu di-unpivot (melt) menjadi format **long** agar bisa digabung dengan dataset lain berdasarkan tanggal.

In [10]:
NAMA_BULAN_TO_NUM = {
    "Januari": 1, "Februari": 2, "Maret": 3,    "April": 4,
    "Mei": 5,     "Juni": 6,     "Juli": 7,      "Agustus": 8,
    "September": 9,"Oktober": 10, "November": 11, "Desember": 12,
}

def normalize_nama_daerah(nama: str) -> str:
    """
    Menstandarkan format nama daerah:
    - Strip whitespace
    - Title case
    - Normalisasi singkatan umum
    """
    if not isinstance(nama, str):
        return np.nan
    nama = nama.strip().title()
    # Normalisasi singkatan
    replacements = {
        "Kab ": "Kab. ", "Kota ": "Kota ",
        "Dki ": "DKI ", "D.i ": "D.I. ",
    }
    for old, new in replacements.items():
        nama = nama.replace(old, new)
    return nama


def parse_inflasi_single_year(df: pd.DataFrame, year: int) -> pd.DataFrame:
    """
    Mengubah satu file inflasi (format pivot/wide) menjadi format long.

    Struktur raw:
      - Baris 0–2: header meta (judul, tahun, nama bulan)
      - Baris 3+:  nama daerah (kolom 0) + nilai inflasi per bulan (kolom 1–12)
      - Kolom 13: nilai tahunan (di-drop)

    Returns
    -------
    pd.DataFrame long dengan kolom:
        nama_daerah, bulan, bulan_nama, tahun, inflasi_persen
    """
    df = df.copy()

    # Ekstrak nama kolom bulan dari baris ke-2
    header_row = df.iloc[2].tolist()          # ['NaN', 'Januari', 'Februari', ...]
    bulan_cols  = header_row[1:13]            # 12 kolom bulan (abaikan Tahunan)

    # Ambil hanya data mulai baris ke-3, kolom 0 (daerah) + kolom 1–12 (bulan)
    data = df.iloc[3:, [0] + list(range(1, 13))].copy()
    data.columns = ["nama_daerah"] + bulan_cols

    # Hapus baris yang seluruh nilai bulannya NaN atau '-'
    data = data.dropna(subset=["nama_daerah"])
    data = data[data["nama_daerah"].astype(str).str.strip() != ""]

    # Ubah ke format long (melt)
    data_long = data.melt(
        id_vars=["nama_daerah"],
        value_vars=bulan_cols,
        var_name="bulan_nama",
        value_name="inflasi_persen"
    )

    # Bersihkan nilai inflasi: '-' → NaN, lalu ke numerik
    data_long["inflasi_persen"] = (
        data_long["inflasi_persen"]
        .astype(str)
        .str.strip()
        .replace("-", np.nan)
    )
    data_long["inflasi_persen"] = pd.to_numeric(data_long["inflasi_persen"], errors="coerce")

    # Hapus baris dengan inflasi NaN (data tidak tersedia)
    data_long = data_long.dropna(subset=["inflasi_persen"])

    # Tambah kolom tahun dan nomor bulan
    data_long["tahun"] = year
    data_long["bulan"] = data_long["bulan_nama"].map(NAMA_BULAN_TO_NUM)

    # Normalisasi nama daerah
    data_long["nama_daerah"] = data_long["nama_daerah"].apply(normalize_nama_daerah)

    # Hapus duplikat
    data_long = data_long.drop_duplicates(subset=["nama_daerah", "tahun", "bulan"])

    # Kolom tanggal (hari 1 setiap bulan) & year_month
    data_long["tanggal"] = pd.to_datetime({
        "year" : data_long["tahun"],
        "month": data_long["bulan"],
        "day"  : 1
    })
    data_long["year_month"] = data_long["tanggal"].dt.to_period("M")

    return data_long[["nama_daerah", "tahun", "bulan", "bulan_nama", "tanggal", "year_month", "inflasi_persen"]]


def clean_inflasi_all_years(raw_dict: dict) -> pd.DataFrame:
    """
    Membersihkan dan menggabungkan semua file inflasi (2020–2026) menjadi satu DataFrame long.

    Returns
    -------
    pd.DataFrame gabungan seluruh tahun.
    """
    frames = []
    for year, df in raw_dict.items():
        df_long = parse_inflasi_single_year(df, year)
        frames.append(df_long)
        logger.info(f"  [Inflasi {year}] Parsed → {len(df_long):,} baris, {df_long['nama_daerah'].nunique()} daerah")

    combined = pd.concat(frames, ignore_index=True)

    # Sorting
    combined = combined.sort_values(["nama_daerah", "tahun", "bulan"]).reset_index(drop=True)

    # Hapus duplikat global
    before = len(combined)
    combined = combined.drop_duplicates(subset=["nama_daerah", "tahun", "bulan"])
    logger.info(f"  Duplikat dihapus (global): {before - len(combined)} baris")

    logger.info(f"[Inflasi] Cleaning selesai → shape {combined.shape}")
    return combined


clean_inflasi_df = clean_inflasi_all_years(raw_inflasi)
print(clean_inflasi_df.head(10).to_string())
print(f"\nShape       : {clean_inflasi_df.shape}")
print(f"Rentang     : {clean_inflasi_df['tanggal'].min()} s.d. {clean_inflasi_df['tanggal'].max()}")
print(f"Jumlah daerah: {clean_inflasi_df['nama_daerah'].nunique()}")

2026-06-05 18:50:18 [INFO]   [Inflasi 2020] Parsed → 1,092 baris, 91 daerah
2026-06-05 18:50:18 [INFO]   [Inflasi 2021] Parsed → 1,092 baris, 91 daerah
2026-06-05 18:50:18 [INFO]   [Inflasi 2022] Parsed → 1,092 baris, 91 daerah
2026-06-05 18:50:18 [INFO]   [Inflasi 2023] Parsed → 1,092 baris, 91 daerah
2026-06-05 18:50:18 [INFO]   [Inflasi 2024] Parsed → 1,812 baris, 151 daerah
2026-06-05 18:50:18 [INFO]   [Inflasi 2025] Parsed → 1,812 baris, 151 daerah
2026-06-05 18:50:18 [INFO]   [Inflasi 2026] Parsed → 302 baris, 151 daerah
2026-06-05 18:50:18 [INFO]   Duplikat dihapus (global): 0 baris
2026-06-05 18:50:18 [INFO] [Inflasi] Cleaning selesai → shape (8294, 7)

  nama_daerah  tahun  bulan bulan_nama    tanggal year_month  inflasi_persen
0  Banyuwangi   2020      1    Januari 2020-01-01    2020-01            0.51
1  Banyuwangi   2020      2   Februari 2020-02-01    2020-02            0.10
2  Banyuwangi   2020      3      Maret 2020-03-01    2020-03            0.27
3  Banyuwangi   2020      4      April 2020-04-01    2020-04            0.24
4  Banyuwangi   2020      5        Mei 2020-05-01    2020-05            0.02
5  Banyuwangi   2020      6       Juni 2020-06-01    2020-06            0.06
6  Banyuwangi   2020      7       Juli 2020-07-01    2020-07            0.01
7  Banyuwangi   2020      8    Agustus 2020-08-01    2020-08           -0.01
8  Banyuwangi   2020      9  September 2020-09-01    2020-09           -0.17
9  Banyuwangi   2020     10    Oktober 2020-10-01    2020-10            0.07

Shape       : (8294, 7)
Rentang     : 2020-01-01 00:00:00 s.d. 2026-02-01 00:00:00
Jumlah daerah: 151

### 4.4 Integrasi Dataset

Menggabungkan tiga dataset berdasarkan kolom `year_month`:
1. Inflasi Indonesia (long format, per daerah)
2. Harga minyak global (USD)
3. Kurs USD/IDR

Selain itu, dihitung juga **harga minyak dalam Rupiah**:  
`harga_minyak_idr = harga_minyak_usd × kurs_usd_idr`

In [11]:
def transform_currency(df: pd.DataFrame,
                        col_usd: str,
                        col_kurs: str,
                        col_idr: str) -> pd.DataFrame:
    """
    Menghitung harga dalam Rupiah dari harga USD dan kurs USD/IDR.

    Parameters
    ----------
    df       : DataFrame yang sudah mengandung kolom harga USD dan kurs.
    col_usd  : Nama kolom harga dalam USD.
    col_kurs : Nama kolom kurs USD/IDR.
    col_idr  : Nama kolom output (harga dalam IDR).

    Returns
    -------
    DataFrame dengan kolom `col_idr` yang baru.
    """
    df = df.copy()
    df[col_idr] = df[col_usd] * df[col_kurs]
    df[col_idr] = df[col_idr].round(2)
    logger.info(f"Kolom '{col_idr}' berhasil dihitung.")
    return df


def merge_datasets(
    df_inflasi: pd.DataFrame,
    df_oil    : pd.DataFrame,
    df_kurs   : pd.DataFrame
) -> pd.DataFrame:
    """
    Menggabungkan dataset inflasi, harga minyak, dan kurs USD/IDR.

    Strategi join:
    - LEFT JOIN inflasi ← oil (berdasarkan year_month)
    - LEFT JOIN ← kurs (berdasarkan year_month)

    Returns
    -------
    pd.DataFrame terintegrasi.
    """
    # Siapkan subset oil & kurs untuk join
    oil_join = df_oil[["year_month", "harga_minyak_usd", "perubahan_persen_minyak"]]
    kurs_join = df_kurs[["year_month", "kurs_usd_idr", "perubahan_persen_kurs"]]

    # Join
    df = df_inflasi.merge(oil_join,  on="year_month", how="left")
    df = df.merge(kurs_join, on="year_month", how="left")

    before = len(df)
    n_no_oil  = df["harga_minyak_usd"].isna().sum()
    n_no_kurs = df["kurs_usd_idr"].isna().sum()
    logger.info(f"  Baris tanpa data oil  : {n_no_oil:,}")
    logger.info(f"  Baris tanpa data kurs : {n_no_kurs:,}")

    # Hitung harga minyak dalam IDR
    df = transform_currency(df,
                            col_usd="harga_minyak_usd",
                            col_kurs="kurs_usd_idr",
                            col_idr="harga_minyak_idr")

    logger.info(f"Integrasi selesai → shape {df.shape}")
    return df


merged_df = merge_datasets(clean_inflasi_df, clean_oil_df, clean_kurs_df)
print(merged_df.head(5).to_string())
print(f"\nShape: {merged_df.shape}")
print(f"Missing values:\n{merged_df.isnull().sum().to_string()}")

2026-06-05 18:50:24 [INFO]   Baris tanpa data oil  : 0
2026-06-05 18:50:24 [INFO]   Baris tanpa data kurs : 0
2026-06-05 18:50:24 [INFO] Kolom 'harga_minyak_idr' berhasil dihitung.
2026-06-05 18:50:24 [INFO] Integrasi selesai → shape (8294, 12)

  nama_daerah  tahun  bulan bulan_nama    tanggal year_month  inflasi_persen  harga_minyak_usd  perubahan_persen_minyak  kurs_usd_idr  perubahan_persen_kurs  harga_minyak_idr
0  Banyuwangi   2020      1    Januari 2020-01-01    2020-01            0.51             51.56                  -15.135       13650.0                  -1.66         703794.00
1  Banyuwangi   2020      2   Februari 2020-02-01    2020-02            0.10             44.76                  -13.189       14340.0                   5.05         641858.40
2  Banyuwangi   2020      3      Maret 2020-03-01    2020-03            0.27             20.48                  -54.245       16300.0                  13.67         333824.00
3  Banyuwangi   2020      4      April 2020-04-01    2020-04            0.24             18.84                   -8.008       14825.0                  -9.05         279303.00
4  Banyuwangi   2020      5        Mei 2020-05-01    2020-05            0.02             35.49                   88.376       14575.0                  -1.69         517266.75

Shape: (8294, 12)
Missing values:
nama_daerah                0
tahun                      0
bulan                      0
bulan_nama                 0
tanggal                    0
year_month                 0
inflasi_persen             0
harga_minyak_usd           0
perubahan_persen_minyak    0
kurs_usd_idr               0
perubahan_persen_kurs      0
harga_minyak_idr           0

### 4.5 Validasi Data Final

Memastikan dataset akhir bersih, konsisten, dan siap untuk dimuat ke database.

In [12]:
def validate_final_dataset(df: pd.DataFrame) -> bool:
    """
    Melakukan serangkaian validasi terhadap DataFrame final.

    Checks:
    - Tidak ada duplikat kunci (nama_daerah + year_month)
    - Kolom wajib tidak seluruhnya kosong
    - Rentang nilai masuk akal

    Returns
    -------
    True jika semua validasi lulus, False jika ada yang gagal.
    """
    passed = True
    print("=" * 55)
    print("  VALIDASI DATASET FINAL")
    print("=" * 55)

    # 1. Cek duplikat kunci
    n_dup = df.duplicated(subset=["nama_daerah", "year_month"]).sum()
    status = "Pass" if n_dup == 0 else "Fail"
    print(f"{status} Duplikat (nama_daerah + year_month) : {n_dup}")
    if n_dup > 0: passed = False

    # 2. Cek kolom wajib tidak sepenuhnya NaN
    required_cols = ["nama_daerah", "tahun", "bulan", "inflasi_persen",
                     "harga_minyak_usd", "kurs_usd_idr", "harga_minyak_idr"]
    for col in required_cols:
        if col not in df.columns:
            print(f"Kolom wajib tidak ada: {col}")
            passed = False
        else:
            n_null = df[col].isnull().sum()
            pct    = n_null / len(df) * 100
            icon   = "Warning" if n_null > 0 else "Pass"
            print(f"{icon} {col:35s}: {n_null:,} null ({pct:.1f}%)")

    # 3. Cek rentang nilai
    if "harga_minyak_usd" in df.columns:
        min_p, max_p = df["harga_minyak_usd"].min(), df["harga_minyak_usd"].max()
        ok = 0 < min_p < max_p < 500
        print(f"{'Pass' if ok else 'Fail'} Harga minyak USD range: ${min_p:.2f} – ${max_p:.2f}")
        if not ok: passed = False

    if "kurs_usd_idr" in df.columns:
        min_k, max_k = df["kurs_usd_idr"].min(), df["kurs_usd_idr"].max()
        ok = 1000 < min_k < max_k < 30000
        print(f"{'Pass' if ok else 'Fail'} Kurs USD/IDR range   : {min_k:,.0f} – {max_k:,.0f}")
        if not ok: passed = False

    print("=" * 55)
    print(f"  Hasil Validasi : {'LULUS' if passed else 'ADA MASALAH'}")
    print("=" * 55)
    return passed


is_valid = validate_final_dataset(merged_df)

=======================================================
  VALIDASI DATASET FINAL
=======================================================
Pass Duplikat (nama_daerah + year_month) : 0
Pass nama_daerah                        : 0 null (0.0%)
Pass tahun                              : 0 null (0.0%)
Pass bulan                              : 0 null (0.0%)
Pass inflasi_persen                     : 0 null (0.0%)
Pass harga_minyak_usd                   : 0 null (0.0%)
Pass kurs_usd_idr                       : 0 null (0.0%)
Pass harga_minyak_idr                   : 0 null (0.0%)
Pass Harga minyak USD range: $18.84 – $111.91
Pass Kurs USD/IDR range   : 13,650 – 16,785
=======================================================
  Hasil Validasi : LULUS
=======================================================

## 5. 💾 Load — Simpan ke PostgreSQL Aiven

Menyimpan DataFrame final ke tabel PostgreSQL menggunakan **SQLAlchemy** + **psycopg2**.

Koneksi menggunakan credential dari environment variable `.env` untuk keamanan.  
Jika tabel sudah ada, data akan **direplace** (`if_exists='replace'`).

In [13]:
def build_connection_string(config: dict) -> str:
    """
    Membangun connection string PostgreSQL dari dictionary konfigurasi.

    Format: postgresql+psycopg2://user:password@host:port/database?sslmode=require
    """
    return (
        f"postgresql+psycopg2://"
        f"{config['user']}:{config['password']}"
        f"@{config['host']}:{config['port']}"
        f"/{config['database']}"
        f"?sslmode=require"
    )


def save_to_postgresql(
    df        : pd.DataFrame,
    table_name: str,
    db_config : dict,
    if_exists : str = "replace",
    chunksize : int = 1000
) -> bool:
    """
    Menyimpan DataFrame ke tabel PostgreSQL menggunakan SQLAlchemy.

    Parameters
    ----------
    df         : DataFrame yang akan disimpan.
    table_name : Nama tabel di PostgreSQL.
    db_config  : Dictionary berisi host, port, database, user, password.
    if_exists  : Strategi jika tabel sudah ada ('replace' / 'append').
    chunksize  : Jumlah baris per batch insert.

    Returns
    -------
    True jika berhasil, False jika gagal.
    """
    # Validasi config
    missing = [k for k, v in db_config.items() if not v]
    if missing:
        logger.error(f"Credential belum diisi: {missing}. Proses Load di-skip.")
        return False

    conn_str = build_connection_string(db_config)

    try:
        df = df.copy()
        for col in df.columns:
            if pd.api.types.is_period_dtype(df[col]):
                df[col] = df[col].astype(str)
                logger.info(f"  Konversi Period → str : kolom '{col}'")
            elif pd.api.types.is_bool_dtype(df[col]):
                df[col] = df[col].astype(bool)
        
        engine = create_engine(conn_str, connect_args={"connect_timeout": 10})

        logger.info(f"Mencoba koneksi ke database '{db_config['database']}' ...")

        with engine.connect() as conn:
            logger.info("Koneksi berhasil!")

            # Drop & buat ulang tabel jika 'replace'
            logger.info(f"Memuat {len(df):,} baris ke tabel '{table_name}' (mode: {if_exists}) ...")

            df.to_sql(
                name      = table_name,
                con       = engine,
                if_exists = if_exists,
                index     = False,
                chunksize = chunksize,
                method    = "multi"
            )

            # Validasi jumlah baris setelah upload
            result = conn.execute(text(f"SELECT COUNT(*) FROM {table_name}"))
            row_count = result.scalar()

        logger.info(f"Upload selesai. Jumlah baris di '{table_name}': {row_count:,}")
        return True

    except Exception as e:
        logger.error(f"Gagal menyimpan ke PostgreSQL: {e}")
        return False
    finally:
        engine.dispose()
        logger.info("Koneksi database ditutup.")

In [14]:
# ── Eksekusi Load ─────────────────────────────────────────────────────────────
if is_valid:
    success = save_to_postgresql(
        df         = merged_df,
        table_name = TABLE_NAME,
        db_config  = DB_CONFIG,
        if_exists  = "replace",
        chunksize  = 1000
    )
    if success:
        print(f"\nDataset berhasil dimuat ke PostgreSQL Aiven → tabel '{TABLE_NAME}'")
    else:
        print("\nLoad ke database di-skip (cek credential .env atau koneksi internet).")
else:
    logger.warning("Dataset tidak lulus validasi. Proses Load dibatalkan.")

2026-06-05 18:50:35 [INFO]   Konversi Period → str : kolom 'year_month'
2026-06-05 18:50:36 [INFO] Mencoba koneksi ke database 'defaultdb' ...
2026-06-05 18:50:37 [INFO] Koneksi berhasil!
2026-06-05 18:50:37 [INFO] Memuat 8,294 baris ke tabel 'inflasi_minyak_indonesia' (mode: replace) ...
2026-06-05 18:50:43 [INFO] Upload selesai. Jumlah baris di 'inflasi_minyak_indonesia': 8,294
2026-06-05 18:50:43 [INFO] Koneksi database ditutup.

Dataset berhasil dimuat ke PostgreSQL Aiven → tabel 'inflasi_minyak_indonesia'

## 6. 📊 Ringkasan Proses ETL

Tampilkan ringkasan akhir dari seluruh pipeline.

In [ ]:
print("=" * 60)
print("  RINGKASAN ETL PIPELINE")
print("=" * 60)
print(f"  Tanggal dijalankan : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f"  Sumber data inflasi: {len(raw_inflasi)} file (2020–2026)")
print()
print("  [EXTRACT]")
print(f"    Harga Minyak  : {len(raw_oil):,} baris")
print(f"    Kurs USD/IDR  : {len(raw_kurs):,} baris")
print(f"    Inflasi (raw) : {sum(len(v) for v in raw_inflasi.values()):,} baris (total dari semua file)")
print()
print("  [TRANSFORM]")
print(f"    Oil bersih    : {len(clean_oil_df):,} baris")
print(f"    Kurs bersih   : {len(clean_kurs_df):,} baris")
print(f"    Inflasi bersih: {len(clean_inflasi_df):,} baris ({clean_inflasi_df['nama_daerah'].nunique()} daerah)")
print(f"    Merged        : {len(merged_df):,} baris × {merged_df.shape[1]} kolom")
print()
print("  [LOAD]")
print(f"    Tabel target  : {TABLE_NAME}")
print(f"    Status        : {'Berhasil' if is_valid else '⚠️ Di-skip (validasi gagal atau credential kosong)'}")
print()
print("  Kolom Dataset Final:")
for col in merged_df.columns:
    print(f"    - {col}")
print("=" * 60)

In [16]:
# Load environment variables
load_dotenv()

db_config = {
    "host"    : os.getenv("AIVEN_HOST"),
    "port"    : os.getenv("AIVEN_PORT", "5432"),
    "database": os.getenv("AIVEN_DATABASE"),
    "user"    : os.getenv("AIVEN_USER"),
    "password": os.getenv("AIVEN_PASSWORD"),
}


query = "SELECT * FROM inflasi_minyak_indonesia LIMIT 5"

conn_str = f"postgresql+psycopg2://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['database']}?sslmode=require"

try:
    logger.info(f"[INFO] Mencoba koneksi ke database '{db_config['database']}' ...")
    engine = create_engine(conn_str, connect_args={"connect_timeout": 10})
    
    with engine.connect() as conn:
        logger.info("[INFO] Koneksi berhasil! Mengambil data...")
        df = pd.read_sql(query, conn)
        
    logger.info(f"[INFO] Data berhasil ditarik: {df.shape[0]} baris.")
    display(df.head())
    
except Exception as e:
    logger.error(f"[INFO] Gagal mengambil data dari database: {e}")

2026-06-06 03:27:54 [INFO] [INFO] Mencoba koneksi ke database 'defaultdb' ...
2026-06-06 03:27:55 [INFO] [INFO] Koneksi berhasil! Mengambil data...
2026-06-06 03:27:56 [INFO] [INFO] Data berhasil ditarik: 5 baris.

,nama_daerah,tahun,bulan,bulan_nama,tanggal,year_month,inflasi_persen,harga_minyak_usd,perubahan_persen_minyak,kurs_usd_idr,perubahan_persen_kurs,harga_minyak_idr
0,Banyuwangi,2020,1,Januari,2020-01-01,2020-01,0.51,51.56,-15.135,13650.0,-1.66,703794.00
1,Banyuwangi,2020,2,Februari,2020-02-01,2020-02,0.10,44.76,-13.189,14340.0,5.05,641858.40
2,Banyuwangi,2020,3,Maret,2020-03-01,2020-03,0.27,20.48,-54.245,16300.0,13.67,333824.00
3,Banyuwangi,2020,4,April,2020-04-01,2020-04,0.24,18.84,-8.008,14825.0,-9.05,279303.00
4,Banyuwangi,2020,5,Mei,2020-05-01,2020-05,0.02,35.49,88.376,14575.0,-1.69,517266.75